version: '3.8'

services:
  crypto_parser:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto_parser
    environment:
      - DATABASE_URL=postgres://pricemonitor:password@db:5432/pricemonitor
    depends_on:
      - db
      - mailcatcher
    volumes:
      - .:/app
    command: ["/app/wait-for-it.sh", "db:5432", "--", "python", "main.py"]

  mp_parser:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mp_parser
    environment:
      - DATABASE_URL=postgres://pricemonitor:password@db:5432/pricemonitor
    depends_on:
      - db
      - mailcatcher
    volumes:
      - .:/app
    command: ["/app/wait-for-it.sh", "db:5432", "--", "python", "mp_main.py"]

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: pricemonitor
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pricemonitor
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pricemonitor"]
      interval: 10s
      retries: 5
      timeout: 5s

  mailcatcher:
    image: sj26/mailcatcher
    container_name: mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
    command: mailcatcher --ip=0.0.0.0

volumes:
  postgres_data:
